// @flow

import fs from 'fs';
import path from 'path';
import prettier from 'prettier';
import os from 'os';

import breakpoints, { breakpointsMap } from '../src/breakpoints';

const fileName = path.join(__dirname, '..', 'src', 'utilities', 'display.css');
if (fs.existsSync(fileName)) {
  fs.unlinkSync(fileName);
}

const displayValues = ['block', 'inline', 'inline-block', 'flex', 'grid'];

let fileContent = `/* This file is autogenerated. Do not modify manually */${os.EOL}`;

for (const bp of breakpointsMap) {
  for (const value of displayValues) {
    if (bp === '') {
      fileContent += `.u-display-${value} {display: ${value}}`;
    } else {
      fileContent += `${breakpoints[bp]}{.u-display-${value}-${bp} {display: ${value}}}`;
    }
  }
}

fs.writeFileSync(fileName, prettier.format(fileContent, { filepath: 'display.css' }));
