"""
Tests via Jest.
"""

load("@npm//jest-cli:index.bzl", "jest", _jest_test = "jest_test")

def jest_test(name, srcs, deps, jest_config, extra_args = [], **kwargs):
    """A macro around the autogenerated jest_test rule

    Args:
        name: name of the target
        srcs: sources to test
        deps: dependencies necessary for the target to build/test
        jest_config: Jest config file
        extra_args: Workspace specific args to jest
        **kwargs: other Jest arguments
    """
    templated_args = [
        "--no-cache",
        "--no-watchman",
        "--ci",
        "--colors",
    ] + extra_args
    templated_args.extend(["--config", "$(rootpath %s)" % jest_config])
    for src in srcs:
        templated_args.extend(["--runTestsByPath", "$(rootpath %s)" % src])

    data = [jest_config] + srcs + deps
    _jest_test(
        name = name,
        data = data,
        templated_args = templated_args,
        **kwargs
    )

    # This rule is used specifically to update snapshots via `bazel run`
    jest(
        name = "%s.update" % name,
        data = data,
        templated_args = templated_args + ["-u"],
        **kwargs
    )
